### ISSUE TITLE
Deleting curses

### ISSUE THREAD

**Issue by Ilyza91** [FloricSpacer/AbyssDiver#2]
For shrine 3 we now simply delete the curse from the stored list. But this actual doesn't reverse the curse affects as e.g. the stat changes of a dizzying heights are still present. To properly do this we have to write a separate (and lengthy)  piece of code that checks if the curse is a stat change curse and apply the reverse changes. The upside is that if we do this that we basically have also implemented the managed misfortune. Maybe there is more efficient solution, but I don't see it at the moment

**Comment by emmeken** [comment]
Maybe instead of changing a variable when a curse is picked up, stats could be computed instead. So for example instead of having a `height` variable there would be a `get_height()` function that returns the current main character height computed from the initial height and active curses.

I think recomputing is more reliable, since stat changes may not always be simple to reverse. For example, a stat might be clipped to a minimum or maximum value, in which case taking on a curse might have no or a reduced effect. If removing the curse is done by applying the opposite stat change, you might not end up in the same situation as before. Another case is where one change overwrites another: let's say you get cat ears after bunny ears, then removing the cat ears curse should restore the bunny ears, not go back to human ears.

**Comment by Ilyza91** [comment]
I see what you mean. That does require a rewrite of all stat changing curses though, but it would be better in the end.

**Comment by emmeken** [comment]
It's possible to do the rewrite one stat at a time, that way the work can be split up and we can verify the design.

**Comment by Ilyza91** [comment]
Yeah I was thinking along the same lines. I wanted to start with height and age as at least for height the infrastructure is sort of there already and age is closely connected to height so it's better to change those at the same time

**Comment by Ilyza91** [comment]
So I made a 'shadow' system for the height widget for now to test the whole concept. It seems to work at the moment eventhough it took me a fair bit of effort to get it to do exactly what I wanted, which made me question what we exactly wanted.
So first I want to clearify what I didn't do:
I didn't change the existing curse passages, height widget or implemented anything with respect to the random curse and cherry curse variations

This is what I did do:
I made 'shadow/test' curses and a "shadow/test" height widget you could take to test the system. The curses I considered are dizzying height, minish-ish and collosal-able (did I forget any?). I removed the stat changes from all these curses and just let them push the curses to the curse list. For dizzying height I had to make two separate curses to govern the increase and decrease effect separately, but at some point realized we don't really need that if you just introduce a variable to track whether you're increasing or decreasing. I left the split in for now, as I somewhat liked that you could see if you have the increasing version or the decreasing version of dizzying heights, but the code would be more efficient without the split of course. So that's one point of consideration. 
Another is the foraging. I now solved it by letting the foraging being the only thing that affects app.height so it plays nice with the new height widget while at the same time not appearing in the curse list. This is all fine for the height, but I was already with half a mind thinking about the age parameter and there it actually maters in which order you do the foraging and take the regression curses, because of the age jump a first regression curse has.  So do we want to keep it that way? Because then we need a combined forage and curse list to track the order. Or do we want a variation of how it is done with height, were we have a set order of calculating things. For example the accumulated foraging penalty is always calculated after the accumulated curse penalties. 
A minor adjustment I made is that the size handicap now correctly only activated if you are minish AND don't have companions. I had half a mind about making the size handicap not exclusive to minish or colassable but make them directly height dependent, as this is in the end what the text explains as the reason for the handicap, but I left them exclusive to those curses as for now
Last minor adjustment was that I took away the layer tags from the doll passages. I can't remember putting them there in the first place, but especially now it's easier to find without the tags for those two passages.

**Comment by emmeken** [comment]
I'll have a look at the code changes in a bit, but first I'd like to tell you about a Git feature that can be useful for situations like this, where you have experimental changes that need some testing or review before they're ready to use in a release. If you add those changes in a separate branch, you don't have to worry about breaking anything, since the commits on the branch won't affect other people or releases until that branch is merged. It's like an alternate timeline in a sci-fi story where you can decide later whether the events there should become canon (merged) or not (left as a dangling branch).

For a hands-on tutorial on branches, look [here](https://gitimmersion.com/lab_24.html). Note that our development branch is currently called `preview` instead of `master` or `main` because I originally created it as a proof of concept; we should probably rename it at some point, but maybe after you and FloricSpacer are a bit more familiar with Git.

**Comment by emmeken** [comment]
I added some code review comments on the commit itself.

> I made 'shadow/test' curses and a "shadow/test" height widget you could take to test the system. The curses I considered are dizzying height, minish-ish and collosal-able (did I forget any?). I removed the stat changes from all these curses and just let them push the curses to the curse list. For dizzying height I had to make two separate curses to govern the increase and decrease effect separately, but at some point realized we don't really need that if you just introduce a variable to track whether you're increasing or decreasing. I left the split in for now, as I somewhat liked that you could see if you have the increasing version or the decreasing version of dizzying heights, but the code would be more efficient without the split of course. So that's one point of consideration.

It all depends on the game design: is a player put on a fixed shrinking or growing path after the initial choice or is it possible later height adjustments to go in the other direction as well? The CYAO uses the single direction approach; unless we have a strong reason to deviate from it, it's probably best to follow the CYAO design.

> Another is the foraging. I now solved it by letting the foraging being the only thing that affects app.height so it plays nice with the new height widget while at the same time not appearing in the curse list.

If we follow the CYAO literally, we'd have to apply age and male/female modifiers first and foraging and curse modifiers last, since otherwise the change in height doesn't exactly match the predicted amount. However, I don't think the CYAO rules work when taken literally, as you could end up at a negative height when shrinking after taking on minish-ish (10-20cm minus 5x5cm from Dizzying Heights).

If we're not going to follow the CYAO literally, I think we should remove the exact size descriptions from the curse text and instead say that for example Dizzying Heights will grow/shrink you a bit and narrate your new height after you have taken on that curse.

If I understand your approach correctly, it works like this:
- start with the original adult height (from character generation)
- apply foraging and Dizzying Heights as absolute modifiers
- apply colossal/mini as linear relative modifiers
- apply age/gender as linear relative modifiers

I think the only alternative that would make sense would be:
- start with the original adult height (from character generation)
- apply age/gender as linear relative modifiers
- apply foraging and Dizzying Heights as absolute modifiers
- apply colossal/mini as linear relative modifiers

This would stay a bit closer to the CYAO text, since in the absence of colossal/mini, every Dizzying Heights level would be 5cm. I don't know if that makes it better though; there is also something to be said for foraging and Dizzying Heights affecting taller characters more.

Regarding the current implementation, if I simplify the formula, I get this:
```
$height_adult = $app.oheight * (1.0 + 0.01525 * (5 * $female_start - $genderlvl))
              + $height_change * 0.92375 * $female_start
```
This would mean that `$height_change` has no effect on characters that started male (`$female_start` = 0), which sounds odd. It's possible I made a mistake during simplifying, but I did it twice and got the same result.

> This is all fine for the height, but I was already with half a mind thinking about the age parameter and there it actually maters in which order you do the foraging and take the regression curses, because of the age jump a first regression curse has. So do we want to keep it that way?

The jump feels rather arbitrary to me. I think a relative regression would make more sense. So instead of -1, -2, -3 and -4 years it could be a factor of 0.95, 0.90, 0.85 and 0.80 respectively (applied cumulatively by multiplying). It would have more or less the same result on a 20-something character, but if you'd start with an older character the changes would be more gradual.

> Because then we need a combined forage and curse list to track the order. Or do we want a variation of how it is done with height, were we have a set order of calculating things. For example the accumulated foraging penalty is always calculated after the accumulated curse penalties.

If we make everything factors, the order no longer matters: whatever order you multiply the numbers in, the result will be the same.

> A minor adjustment I made is that the size handicap now correctly only activated if you are minish AND don't have companions. I had half a mind about making the size handicap not exclusive to minish or colassable but make them directly height dependent, as this is in the end what the text explains as the reason for the handicap, but I left them exclusive to those curses as for now

For now that's probably good enough, but it might be nice in the future to have gradual movement penalties rather than an all or nothing system.

As I wrote in the code comment, I think size handicap should be split off from the height computation code though. Realistically, a party would move at the speed of the slowest character in the party, so it would make sense to compute the movement speed of each companion and then take the minimum of those speeds. Besides size handicap, there could be other things that slow down movement, like malnourishment, untreated wounds or carrying too much.

> Last minor adjustment was that I took away the layer tags from the doll passages. I can't remember putting them there in the first place, but especially now it's easier to find without the tags for those two passages.

Are layer tags in general still useful now that we have a separate source file per layer? I could do a search-and-replace across all files to remove all of them at once.

In general, it's a good idea though to put unrelated changes in separate commits. For example, if at some point you would decide to take a different approach to the height handling and would revert or drop that commit, you wouldn't want to lose any cleanups made around the same time.

**Comment by Ilyza91** [comment]
> If you add those changes in a separate branch, you don't have to worry about breaking anything, since the commits on the branch won't affect other people or releases until that branch is merged. It's like an alternate timeline in a sci-fi story where you can decide later whether the events there should become canon (merged) or not (left as a dangling branch).

That's good to know! I'll have a look at the tutorial as well.

> It all depends on the game design: is a player put on a fixed shrinking or growing path after the initial choice or is it possible later height adjustments to go in the other direction as well? The CYAO uses the single direction approach; unless we have a strong reason to deviate from it, it's probably best to follow the CYAO design.

I agree, the issue I'm raising here is a separate one as in both cases the height change is in 1 direction, doing it in both directions would give you 'free' corruption of course. The issues is more a matter of code clutter. But I'm now inching more towards the double curse setup as it would at least allow you taking a shrinking version, give it to your companion and get a growing version for yourself. Although there are ways to do this with a tracking variable as well it would complicate things a little bit and the code clutter argument becomes less relevant.

>If we follow the CYAO literally, we'd have to apply age and male/female modifiers first and foraging and curse modifiers last, since otherwise the change in height doesn't exactly match the predicted amount. However, I don't think the CYAO rules work when taken literally, as you could end up at a negative height when shrinking after taking on minish-ish (10-20cm minus 5x5cm from Dizzying Heights).

Yeah we also came to that conclusion so we are bending the rules a little bit already. We treat the text as if all absolute height change are applied to your 'normal' adult version instead of your current height. 

>If I understand your approach correctly, it works like this:
(...)
I think the only alternative that would make sense would be:
(...)
This would stay a bit closer to the CYAO text, since in the absence of colossal/mini, every Dizzying Heights level would be 5cm. I don't know if that makes it better though; there is also something to be said for foraging and Dizzying Heights affecting taller characters more.

I would describe the current setup as somewhere in between both of these (and age is not linear, but that's a minor detail in this context) as the absolute changes from dizzying heights and foraging are corrected for after applying the sex scaling, so it roughly always ends up being 5 cm regardless of gender level for each dizzying height curse you take. So in that sense it doesn't matter in which order you take gender reversal and dizzying heights (technically it does but it's hardly to a significant level). 

>Regarding the current implementation, if I simplify the formula, I get this:
$height_adult = $app.oheight * (1.0 + 0.01525 * (5 * $female_start - $genderlvl))
              + $height_change * 0.92375 * $female_start
This would mean that $height_change has no effect on characters that started male ($female_start = 0), which sounds odd. It's possible I made a mistake during simplifying, but I did it twice and got the same result.

I think this is the one you mentioned in its original form 

	<<set $height_adult = $app.oheight +$height_change -$height_change*(1-0.92375)*$female_start -0.01525*$app.oheight*$genderlvl +0.01525*$app.oheight*5*$female_start>>

I strongly suspect you crossed a $height_change term away against a $height_change*$female_start term. So if you don't do that you see that you still have a $height_change that is independent from the $female_start variable.

>The jump feels rather arbitrary to me. I think a relative regression would make more sense. So instead of -1, -2, -3 and -4 years it could be a factor of 0.95, 0.90, 0.85 and 0.80 respectively (applied cumulatively by multiplying). It would have more or less the same result on a 20-something character, but if you'd start with an older character the changes would be more gradual.

This would make life a lot easier, but it does mean we change the rules compared to the original cyoa so I'll let floricspacer judge this first before I start coding something like this. I think the jump now is mainly there because it sets a cap for the foraging as well, while at the same time keeping everything easy to calculate with pen and paper. But yeah, now that's interactive and we can let the computer do the calculations I don't think it's that much of an issue, but again, I'll let floric decide this one.

>For now that's probably good enough, but it might be nice in the future to have gradual movement penalties rather than an all or nothing system.
As I wrote in the code comment, I think size handicap should be split off from the height computation code though. Realistically, a party would move at the speed of the slowest character in the party, so it would make sense to compute the movement speed of each companion and then take the minimum of those speeds. Besides size handicap, there could be other things that slow down movement, like malnourishment, untreated wounds or carrying too much.

The wounds are already in I think and carrying capacity was also something we were considering the tie to the travel time somewhere in the near future. Malnourishment could be a good addition, as long as it is clearly introduced to the player (same for the overburdened penalty of course). I think a gradual system would feel more natural (maybe not for the wounds as those are categorical variables now as well), it's not that much harder to implement than the all or nothing system, but it does mean changing the rules on the size handicap so I'll have floric look at this first as well.

>Are layer tags in general still useful now that we have a separate source file per layer? I could do a search-and-replace across all files to remove all of them at once.

I don't think they have a use other than organizing the passages, but floric always applies those so she would know better.

>In general, it's a good idea though to put unrelated changes in separate commits. For example, if at some point you would decide to take a different approach to the height handling and would revert or drop that commit, you wouldn't want to lose any cleanups made around the same time.

I'll keep this in mind!

Anyway a lot of things to consider here. I'll make a list on how to move forward with the height and age functions based on these discussions when everybody has had their say, so there is a clear directive moving forward with those functions. This last session for me was a bit to freestyle-y because I underestimated the issues a bit and therefore it took me quite some time to get relatively little. In a way it was useful, but it was also a bit inefficient. 
One final thing is that I'm on holidays for the next week and a bit. So I might not be able to do much over that time

**Comment by emmeken** [comment]
> I agree, the issue I'm raising here is a separate one as in both cases the height change is in 1 direction, doing it in both directions would give you 'free' corruption of course. The issues is more a matter of code clutter. But I'm now inching more towards the double curse setup as it would at least allow you taking a shrinking version, give it to your companion and get a growing version for yourself. Although there are ways to do this with a tracking variable as well it would complicate things a little bit and the code clutter argument becomes less relevant.

I didn't think yet about transferring Dizzying Heights to a companion. That raises an interesting question: is the height adjustment direction being frozen because of the presence of the curse, or is it a fate that persists for the entire playthrough? In other words, if a player gets rid of all instances of Dizzying Heights, do they get to choose growing vs shrinking again or are they still locked into the same direction?

While the CYAO doesn't spell this out, I assume that if the player first grows/shrinks from foraging and later takes on Dizzying Heights, the height change will match that of the foraging. So that means that in either design (fate or non-fate), it's possible for the player character to be locked into growing/shrinking through foraging even while having zero counts of Dizzying Heights active.

I assume that the "purity gene" makes companions immune to height changes from foraging. So at least that doesn't add any complications.

I agree that split curses are the best implementation when using the non-fate design, or perhaps even the only correct implementation. For the fate design, the question would be whether companions share the player's fate or whether they would have their own grow/shrink fate. In other words, if a Dizzying Heights that shrunk the player character is transferred to a companion, would that always shrink them as well or could it potentially grow them instead? The latter outcome wouldn't be easy to do with a split curses implementation.

> I would describe the current setup as somewhere in between both of these (and age is not linear, but that's a minor detail in this context) as the absolute changes from dizzying heights and foraging are corrected for after applying the sex scaling, so it roughly always ends up being 5 cm regardless of gender level for each dizzying height curse you take. So in that sense it doesn't matter in which order you take gender reversal and dizzying heights (technically it does but it's hardly to a significant level).

The age height adjustments are not linear with the age, but they are applied as a factor to the adult height, so they are linear with the height. What I mean is that if you have a function `f(x, y) = x^2 * y`, that function is quadratic in `x` but linear in `y`.

> I strongly suspect you crossed a $height_change term away against a $height_change*$female_start term. So if you don't do that you see that you still have a $height_change that is independent from the $female_start variable.

It seems that was indeed the problem; if I do the rewriting again I get this:

```
$height_adult = $app.oheight + $height_change - $height_change * (1 - 0.92375) * $female_start
              - 0.01525 * $app.oheight * $genderlvl + 0.01525 * $app.oheight * 5 * $female_start

$height_adult = $app.oheight - 0.01525 * $app.oheight * $genderlvl + 0.01525 * $app.oheight * 5 * $female_start
              + $height_change - $height_change * (1 - 0.92375) * $female_start

$height_adult = $app.oheight * (1 - 0.01525 * $genderlvl + 0.01525 * 5 * $female_start)
              + $height_change * (1 - (1 - 0.92375) * $female_start)

$height_adult = $app.oheight * (1 - 0.01525 * ($genderlvl - 5 * $female_start))
              + $height_change * (1 - 0.01525 * 5 * $female_start)
```

I think I did the last step incorrectly yesterday.
 
> > The jump feels rather arbitrary to me. I think a relative regression would make more sense. So instead of -1, -2, -3 and -4 years it could be a factor of 0.95, 0.90, 0.85 and 0.80 respectively (applied cumulatively by multiplying). It would have more or less the same result on a 20-something character, but if you'd start with an older character the changes would be more gradual.
> 
> This would make life a lot easier, but it does mean we change the rules compared to the original cyoa so I'll let floricspacer judge this first before I start coding something like this. I think the jump now is mainly there because it sets a cap for the foraging as well, while at the same time keeping everything easy to calculate with pen and paper. But yeah, now that's interactive and we can let the computer do the calculations I don't think it's that much of an issue, but again, I'll let floric decide this one.

I filed issue #4 for this.

> The wounds are already in I think and carrying capacity was also something we were considering the tie to the travel time somewhere in the near future. Malnourishment could be a good addition, as long as it is clearly introduced to the player (same for the overburdened penalty of course). I think a gradual system would feel more natural (maybe not for the wounds as those are categorical variables now as well), it's not that much harder to implement than the all or nothing system, but it does mean changing the rules on the size handicap so I'll have floric look at this first as well.

We don't need to change the way the size handicap works right now. What is relevant now is to separate it from the height calculation in the code.

> > Are layer tags in general still useful now that we have a separate source file per layer? I could do a search-and-replace across all files to remove all of them at once.
> 
> I don't think they have a use other than organizing the passages, but floric always applies those so she would know better.

I filed issue #5 for this.

> Anyway a lot of things to consider here. I'll make a list on how to move forward with the height and age functions based on these discussions when everybody has had their say, so there is a clear directive moving forward with those functions. This last session for me was a bit to freestyle-y because I underestimated the issues a bit and therefore it took me quite some time to get relatively little. In a way it was useful, but it was also a bit inefficient.

It's pretty common to underestimate a problem that you don't fully understand yet. Sometimes you can avoid that by thinking longer ahead of time, but that can also lead to overlooking things that you didn't know are relevant, while they become clear quickly when you actually start changing code.

> One final thing is that I'm on holidays for the next week and a bit. So I might not be able to do much over that time

No problem; thanks for the notice.

**Comment by FloricSpacer** [comment]
> While the CYAO doesn't spell this out, I assume that if the player first grows/shrinks from foraging and later takes on Dizzying Heights, the height change will match that of the foraging. So that means that in either design (fate or non-fate), it's possible for the player character to be locked into growing/shrinking through foraging even while having zero counts of Dizzying Heights active.

Yeah, the way I have it currently working is that both the foraging and Dizzying Heights go in the same direction, which is set the first time you either forage or take the Curse. And there is no way to reverse the direction it is set in the current game.

**Comment by FloricSpacer** [comment]
Also, I'm fine with changing the way height or age work from a variable to a function. 

How do you think we should solve the other things, like gameplay effects and color changes from curses? Should we try to make everything functions?

**Comment by emmeken** [comment]
I think everything that is determined by curses would benefit from being computed (function) rather than being set (state). That way it is much easier to guarantee the right thing happens when curses are transferred or cancelled.

**Comment by Ilyza91** [comment]
Ok I made a function for the age adjustment and I think its a good template for the other appearance variables as well. I thought about making one big shadow list that keeps track of the order of taking curses and foraging and than just let the functions check that list, but in the end I decided to split it up in more specific smaller lists to avoid the code becoming slow. I tested it, so it should work fine but of course there might have been some oversight on my end. I think these were all the instances where your age would get altered:

-pick up age reduction a,b,c
-getting age reduction a,b,c through either cherry mix or cherry curse
-the doll curse
-foraging on layer 3 and foraging while exiting the layer to either side

Curiously enough you can't forage while trapped by the slack slime on layer 3, you simply die if you don't have enough food on you. I could see how this was intentional as you are trapped, so I left that part of the code untouched. But @FloricSpacer let me know if this is actually a bug.

As said, I think this will be a nice template so if either of you have suggestions to improve upon it, now is the time to tell me as I think I might tackle the gender/asset curses next, either tomorrow or the day after.

Did we come to an agreement whether you are locked in shrinking/growing the moment you pick dizzying height or can you choose again if you pass everything off to a companion before taking it again? I would personally favorite the 'faith/destiny' (being locked in after a first choice) option just because of simplicity.

**Comment by emmeken** [comment]
> Ok I made a function for the age adjustment and I think its a good template for the other appearance variables as well. I thought about making one big shadow list that keeps track of the order of taking curses and foraging and than just let the functions check that list, but in the end I decided to split it up in more specific smaller lists to avoid the code becoming slow.

I agree that having a separate list is a good idea, both for performance and to keep things simple and flexible. Maybe in the future we can generalize the curse mechanisms, but for now it's better to consider them independently.

Do we want to apply the effects in the order that they're acquired or in a fixed order? The log approach is necessary to apply them in order, but for a fixed order we could instead use the existing player curses list and a single number for the foraging effects.

The difference is in the hard reset to 20: with the log approach, any foraging effect that doesn't take the player character below 20 will be negated if they ever take on any of the Age Reduction curses. With a fixed order, we'd probably put foraging last and it would always have an impact regardless of when curses are taken on.

From a game play perspective I think both are fine. The implementation for fixed order is a lot simpler though, so that makes it my preference.

> I tested it, so it should work fine but of course there might have been some oversight on my end. I think these were all the instances where your age would get altered:

One alteration not supported yet though is curse removal. Curses removed from the player character would have to be removed from the age log as well. We'd get this for free when using a fixed order implementation that looks in the player curses list directly instead of maintaining a log.

> Did we come to an agreement whether you are locked in shrinking/growing the moment you pick dizzying height or can you choose again if you pass everything off to a companion before taking it again? I would personally favorite the 'faith/destiny' (being locked in after a first choice) option just because of simplicity.

I think the consensus is that locking in the first choice is acceptable. Since it's also easier, that would make it a good pick.

**Comment by Ilyza91** [comment]
I put all the gender/genital related stuff in one function since there are some connections through curses like sex switcheroo and futa change. I did it the same way as the age function. There were some inconsistencies between the cyoa text and the implementation of the asset robustness curses wrt to the penis size. It made it more advantageous to get robustness C and D as a man and then switch gender later if you want to do that, rather than in a different order. This seemed both weird from a gameplay perspective and it almost directly contradicts the cyoa text as well, were the breast cupsizes and penis sizes in inches are in direct lockstep with each other.  So I changed that, and as a bonus I give penis size the same treatment as breast size, meaning you can set it at the beginning and it changes with age. Furthermore,  I think the fixed order is the safe bet for now. And I did everything with the curse removal in the back of my head, as it now automatically works as well when deleting them from the log files as you point out. After all, The curse removal is the whole reason I started doing this :P. But all variables in the $app object have to be pulled from a function first else the whole thing will become a mess. I think the next function will be a miscallanious/inhuman function, with skin, ears and tails all combined. It feels more efficient than to make separate functions for all of them even though they have limited interaction. Finally there is all the non appearance curses which I think can just be removed and we should be fine (the libido curses are I think the only exception) 
Another added advantage is that the transition to putting curses on companions will also be smaller now as we can also give them list and run a similar function. I'll finish the height function later this week.

**Comment by FloricSpacer** [comment]
> Curiously enough you can't forage while trapped by the slack slime on layer 3, you simply die if you don't have enough food on you. I could see how this was intentional as you are trapped, so I left that part of the code untouched. But FloricSpacer let me know if this is actually a bug.

The description specifically says it will force feed you your own food/water reserves, but if you don't have enough on you then it could be a fatal danger, so the idea is that you will always be depleting your food/water when caught and there is a risk of death if unprepared and starving. So it isn't a bug, it's intended.

Also, I really like the log-based approach to age tracking that you added!

**Comment by Ilyza91** [comment]
I think its done now. Although it's so all encompassing that there might still be bugs hiding in specific situations, so be in the look out as well. There should be no stat changing curses outside the functions anymore. So if you see them, it's an oversight on my part and we need to correct it.
For the last appearance based curses I didn't make a seperate log as there are no harvesting options influencing it and it's a lot of curses anyway, so I just used the curse list. So in the end it is structured like this:
Curses and foraging that effect height are in heightCorrected and the corresponding HeightLog (layer4 forage colosable dizzying heights etc) 
Curses and foraging that effect sex/sexual specific body parts are in GenderCorrected  and the corresponding GenderLog (layer1 foraging, asset robustness, sex switcheroo, doll curse etc) 
Curses and foraging that effect age are in AgeCorrected  and the corresponding AgeLog (layer4 foraging, age reduction and doll curse) 
Curses and foraging that effect your mental sexual stat are in LibidoCorrected  and the corresponding LibidoLog (layer2 foraging, libido reinforcement, submissive rectification, semen demon) 
Curses and foraging that effect your appearance not related to your gender are in AppearanceCorrected  and there is no specific log file as these are simply pulled from playerCurses (knife ear, perma-dye, reptail, rainbow swirl, horny etc) 

I also had to make a new descriptive variable eyeColor to accommodate the eye color change from rainbow swirl. It's at the starting page and appearance menu's now as well.

Next week I'm pretty crowded with appointments, but maybe I can squeeze in the time to write a code to remove curses (which can also be used at the shrines) and thus finally get mismanaged fortune working...

**Comment by Ilyza91** [comment]
I squeezed it in today in the end.  Although squeezed might not be the right word :P. Anyway I implemented managed misfortune for the curses on layer 1 (you can pick the relic up in layer 1 for now as well). Please if you have time, look at it/ test it. It's going to bit a bit of chore to implement it for all 96 curses and their random acquisitions, although the template is there now. If there are any issues or things, even if it's just the text, that either of you think should be different, it's better to do it now than later.

**Comment by Ilyza91** [comment]
Code is in under the passage "curseRemoval" in global
