### ISSUE TITLE
Age reduction computation

### ISSUE THREAD

**Issue by emmeken** [FloricSpacer/AbyssDiver#4]
The CYAO states that the first age reduction step always takes the player character to 20, assuming they were older than that originally. This seems a bit arbitrary to me. It probably makes sense to keep the rules simple enough for manual administration by the player, but since we have a computer available for this conversion, we can use more complex rules.

I think a relative regression would make more sense. So instead of -1, -2, -3 and -4 years it could be a factor of 0.95, 0.90, 0.85 and 0.80 respectively (applied cumulatively by multiplying). It would have more or less the same result on a 20-something character, but if you'd start with an older character the changes would be more gradual.

@FloricSpacer: This came up in a discussion of the curse deletion implementation (#2). As this is not just an implementation technique but a change in game play, we'd like to know your thoughts on it.

**Comment by FloricSpacer** [comment]
Hmm, I think the reason that the curses work the current way is so that there is always a cost for someone taking all of them, and it also allows older characters to regress to childhood if they'd like that. Whereas with your new proposed system a 50 year old character could take all 4 curses and end up as 29, which is still solidly an adult. I think the point is that the first curse will always get an older character back to a relatively young, but still adult, age, then further curses beyond that get people to really young ages. Especially given there are people that really enjoy significant age regressions and there are conditions for events and endings that trigger at ages such as 13, I'm not sure that would be a good change. 

So I think that due to the ease of regressing to childhood, the cost to the player for taking many curses, and the ease of access to certain events, I think it makes sense to keep it the way it is now. Is there a particular reason you think a gradual decrease would work better?
