### ISSUE TITLE
Cases of file names

### ISSUE THREAD

**Issue by FloricSpacer** [FloricSpacer/AbyssDiver#7]
I've heard from a Linux user that some images are broken due to the cases not matching in the html and the file name, which causes some of the images to be broken on Linux (which is a case sensitive OS). Would someone be able to change the file references to make them match the files? 

@emmeken This seems like something you may know more about the best way to approach?

**Comment by emmeken** [comment]
I think there are two possible solutions:
- update the file names in the sources to match the current file names of the images
- rename the files in both the sources and the images to only use lower case

The latter is more work right now, but sticking to a lower case only policy would avoid this problem in the future when new images are added. Either solution is fine with me though. Maybe start with fixing the current file names and consider renaming to lower case only for the future.

**Comment by emmeken** [comment]
I've made a list of file names used in the sources and compared that to the files in the full game. Some of them are case mismatches (NPC icons) but there are several mismatches that go beyond upper/lower case as well, like typos, superfluous spaces and even some relics that seem to have been renamed. I've pushed fixes for both of these categories.

The following files are not included with the game and I couldn't find them under a different name either:
- `images/smaragdine-background.png`
- `images/starbackgrounds/stars3.gif`
- `sounds/9 Sunken Ruin.mp3`
- `sounds/10 Quiet and Falling.mp3`
- `sounds/11 Swings and Roundabouts.mp3`
- `sounds/12 Come With Me.mp3`

For the music I guess this is intentional, as those layers aren't implemented yet, but the two backgrounds are actually missing.
